### ISSUE TITLE
Could not edit profile

### ISSUE THREAD

**Issue by N1coB** [BlakeKaufman/BlitzWallet#22]
Android v0.3.0-beta

Tried to change the username but it display an error "you can only have letters and numers..." 

username had only letters, no "öäüß" etc.

Small Issue: Show the app version in the "about" section

![Screenshot_2024-10-11-09-46-44-51_9988ce20f2aef824b5f498c3a46c4541](https://github.com/user-attachments/assets/dd3ba9e6-928c-4dfb-926e-06c30a016752)

**Comment by BlakeKaufman** [comment]
Could you send the username you were trying to enter so I can reproduce the error?
