### ISSUE TITLE
Add PPQ.ai as an app

### ISSUE THREAD

**Issue by N1coB** [BlakeKaufman/BlitzWallet#33]
Add or replace ChatGTP App with PPQ.AI 

PPQ offers diffrent models (Chat and Image Generation) and a good pirvacy

Image Generation:
![image](https://github.com/user-attachments/assets/12e717f3-bfff-437d-993b-7b964d6013e4)
Chat Models:
![image](https://github.com/user-attachments/assets/6ab0adf2-3dc0-4658-a605-c0cf126b05e3)

They offer an API: 

Endpoint
POST https://api.ppq.ai/chat/completions

https://ppq.ai/de

**Comment by BlakeKaufman** [comment]
Interesting. I will have to play around with this. The API seems only to offer text.

**Comment by BlakeKaufman** [comment]
Do you know if they have any docs for the API?

**Comment by N1coB** [comment]
The API is relatively new - I didn't find any
Maybe its best, if you ask him directly: matt.ahlborg@gmail.com
